In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [9]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#aranging in step of 3
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
#arranging matrices in rows and columns
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(1,3,100)

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494

In [29]:
# using numpy to create matrices
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.rand(5,3)

array([[0.92294997, 0.16472158, 0.55491547],
       [0.96354486, 0.40845486, 0.32748386],
       [0.50236186, 0.65822842, 0.27136695],
       [0.15223638, 0.41850314, 0.5052341 ],
       [0.4310234 , 0.94354866, 0.4109299 ]])

In [35]:
np.random.randn(2,4)

array([[-2.12454834,  1.30523094,  0.39295204,  0.53500651],
       [-1.33545454, -1.71359836, -0.59414931, -0.05135074]])

In [39]:
np.random.randint(1,100,10)

array([74, 43, 72, 15, 52, 23, 89, 15, 64, 90])

In [42]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(23,150,10)
ranarr

array([ 70, 141,  41,  62,  93,  76,  32, 137,  83,  53])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr

array([ 70, 141,  41,  62,  93,  76,  32, 137,  83,  53])

In [50]:
ranarr.max()

141

In [51]:
ranarr.min()

32

In [53]:
#to locate the position of the index
ranarr.argmax()

1

In [54]:
ranarr.argmin()

6

In [56]:
# to bring back the no of array
arr.shape

(25,)

In [60]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr.shape

(5, 5)

In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
arr.shape

(5, 5)

In [64]:
arr.dtype

dtype('int32')

In [68]:
 # another method 
from numpy.random import randint 
randint(2,10)

6